version: '3.9'

services:
  db:
    image: mysql:8.2.0
    container_name: debitcharges-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: lucasadmin3010
      MYSQL_USER: lucas
      MYSQL_PASSWORD: lucasadmin3010
      MYSQL_DATABASE: debitcharges
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - debitcharges-network
  debitcharges-api:
    image: lspeixotodev/debitcharges-api
    container_name: debitcharges-api
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/debitcharges?useTimezone=true&serverTimezone=America/Sao_Paulo
      SPRING.DATASOURCE.USERNAME: lucas
      SPRING.DATASOURCE.PASSWORD: lucasadmin3010
    ports:
      - "6060:6060"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - debitcharges-network
networks:
  debitcharges-network:
    driver: bridge